name: Deploy react app
permissions:
  contents: write
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
      - 'hotfix-*'
      - 'feature/**'
    path-ignore:
      - '.github/workflows/*'
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Install node v22.1
        uses: actions/setup-node@v3
        with:
          node-version: 22.1
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: test
        run: npm run test > test.txt
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test.txt
  download-test:
    name: Download test results
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download test
        uses: actions/download-artifact@v4
        with:
          name: test-results
      - name: Print test results
        shell: bash
        run: | 
          value='cat test.txt'
          echo $value

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Install node v22.1
        uses: actions/setup-node@v3
        with:
          node-version: 22.1
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: build
        run: npm run build
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Install node v22.1
        uses: actions/setup-node@v3
        with:
          node-version: 22.1
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          folder: build
          branch: gh-pages
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
