name: docker react app
permissions: 
  contents: write
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: node:22.1
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: test
        run: npm run test
  